Le plugin Weather permet de récupérer les données météorologiques pour une ou plusieurs villes. Il permet entre autre d'avoir les informations de lever et coucher du soleil, de température, de prévision, de vent, etc. Les informations récupérées viennent du site internet openweathermap.

=== Plugin Konfiguration

Après avoir installé le plugin, il faut l'activer puis renseigner votre clef api/ 

Pour obtenir votre clef api il faut aller link:https://home.openweathermap.org[ici], créer un compte et ensuite il faut copier votre clef api dans la zone prévue sur la page de configuration du Plugin.

[IMPORTANT]
Il faut attendre quelques heures ensuite le temps que la clef soit active avant de pouvoir récupérer des informations

=== Geräte Konfiguration

Hier finden sie die ganze Konfiguration Ihrer Geräte:

* *Name der Wetterausrüstung* : Name Ihrer Wetterausrüstung 
* *aktivieren* : erlaubt, Ihr Gerät aktiv zu machen
* *Sichtbar* : macht Ihr Gerät auf dem Armaturenbrett sichtbar
* *Eltern-Objekt* : giebt an welchem Eltern Objekt das Gerät angehört
* *Stadt* : Sie müssen den Namen ihrer Stadt mit den Ländercode eingeben, zum Beispiel Paris, fr
* *Mobil Vollansicht* : ermöglicht alle Wetterinformationen anzuzeigen oder nicht auf Mobile Geräte

Im folgenden finden Sie alle verfügbaren Befehle und die möglichkeit die Zahlenwerte zu archivieren oder nicht.
Le code (numéro) en fonction des conditions est disponible link:https://openweathermap.org/weather-conditions[ici]

Le rafraîchissement des données météo s'effectue toutes les 30 minutes.

[TIP]
Nous vous conseillons de vous rendre link:https://openweathermap.org/find?[ici] afin de vérifier si votre ville, village est connu ou pas. Auquel cas il faudra trouver la ville la plus proche connue et saisir cette dernière dans la configuration de votre équipement pour pouvoir récupérer les informations. 

[TIP]
Une fois la recherche de votre ville réussie le site openweathermap vous montre les informations disponibles et vous devriez avoir dans votre navigateur une url du type https://openweathermap.org/city/2988507. Ce numéro à la fin de l'url peut également être saisi dans l'équipement Jeedom en lieu et place de Paris,fr par exemple  