Le plugin Weather permet de récupérer les données météorologiques pour une ou plusieurs villes. Il permet entre autre d'avoir les informations de lever et coucher du soleil, de température, de prévision, de vent, etc.

=== Plugin Konfiguration

Après avoir installé le plugin, il faut l'activer puis renseigner votre clef api/ 

Pour obtenir votre clef api il faut aller link:https://home.openweathermap.org[ici], et vous créez un compte, ensuite il faut copier votre clef api dans Jeedom.

[IMPORTANT]
Il faut attendre quelques heures ensuite le temps que la clef soit active avant de récupérer des informations

=== Geräte Konfiguration

Hier finden sie die ganze Konfiguration Ihrer Geräte:

* *Name der Wetterausrüstung* : Name Ihrer Wetterausrüstung 
* *aktivieren* : erlaubt, Ihr Gerät aktiv zu machen
* *Sichtbar* : macht Ihr Gerät auf dem Armaturenbrett sichtbar
* *Eltern-Objekt* : giebt an welchem Eltern Objekt das Gerät angehört
* *Stadt* : Sie müssen den Namen ihrer Stadt mit den Ländercode eingeben, zum Beispiel Paris, fr
* *Mobil Vollansicht* : ermöglicht alle Wetterinformationen anzuzeigen oder nicht auf Mobile Geräte

Im folgenden finden Sie alle verfügbaren Befehle und die möglichkeit die Zahlenwerte zu archivieren oder nicht.
Le code (numéro) en fonction des conditions est disponible link:https://openweathermap.org/weather-conditions[ici]

Le rafraîchissement des données météo s'effectue toutes les 30 minutes.